include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - unnecessary_brace_in_string_interps

analyzer:
#   exclude:
#     - path/to/excluded/files/**
