name: ipaddr
description: This library is used to create/poke/manipulate IPv4 and IPv6 addresses and networks.
version: 2.0.1
homepage: https://github.com/yuzumone/ipaddr

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
