name: ipaddr
description: This library is used to create/poke/manipulate IPv4 and IPv6 addresses and networks.
version: 2.1.0
repository: https://github.com/yuzumone/ipaddr

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.5
