name: ipaddr
description: This library is used to create/poke/manipulate IPv4 and IPv6 addresses and networks.
version: 0.1.2
homepage: https://github.com/yuzumone/ipaddr

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0