name: pub dryrun

on: [pull_request]

jobs:
  dryrun:
    if: contains(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish dryrun
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: true
