name: pub dryrun

on: [pull_request]

jobs:
  dryrun:
    if: contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: publish dryrun
        uses: k-paxian/dart-package-publisher@69562ff6bcddfb48d0c637dbf1d5d6b5d1b3a165 # v1.6.1
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          dryRunOnly: true
          skipTests: true
          flutter: false
