name: pub release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: pub publish
        uses: k-paxian/dart-package-publisher@69562ff6bcddfb48d0c637dbf1d5d6b5d1b3a165 # v1.6.1
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          flutter: false
      - name: set version
        id: tag
        run: |
          echo "tag=$(grep '##' CHANGELOG.md | head -n1 | cut -d ' ' -f2)" >> "$GITHUB_OUTPUT"
      - name: set changelog
        id: changelog
        run: |
          cat CHANGELOG.md | sed -n -e '1,/^$/p' | sed -e '/^#/d' -e '/^$/d' > ${{ github.workspace }}-note.txt
      - name: create release note
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body_path: ${{ github.workspace }}-note.txt
          draft: false
          prerelease: false
