name: test and lint

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DanTup/gh-actions/setup-dart@master
      - name: pub get
        run: pub get
      - name: dartfmt
        run: dartfmt -n --set-exit-if-changed .
      - name: dartanalyzer
        run: dartanalyzer --fatal-infos .
      - name: run test
        run: pub run test test/