name: test and lint

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DanTup/gh-actions/setup-dart@master
      - name: pub get
        run: dart pub get
      - name: dartfmt
        run: dart format --set-exit-if-changed .
      - name: dartanalyzer
        run: dart analyze
      - name: run test
        run: dart test
